---
namespace: threescale
sso_project: rh-sso
apicurio_project: apicurio
gogs_project: gogs
microcks_project: microcks
sso_version: ose-v1.4.9
ocp_domain: 3901.openshift.opentlc.com
ocp_apps_domain: apps.3901.openshift.opentlc.com
usersno: 20
threescale: true
apicurio: true
gogs: true
microcks: true
sso: true
user_projects: true
configure_only: false
create_tenants: true
create_realms: true
